### ISSUE TITLE
Top margin for navbar a bit small

### ISSUE THREAD

**Issue by cilliemalan** [RetroRabbit/rabbiteer-intern-project#15]
Cutting it a bit close...

![image](https://cloud.githubusercontent.com/assets/3305301/10244870/b829996e-6902-11e5-957d-d21c2fe6244a.png)

Spacing should be 10px. Probably invalid negative margin...

**Comment by Isabel01** [comment]
The nav bar  is now more appealing ... with complements the Lana and Isabel team :-)
