### ISSUE TITLE
That's not how you spell my name...

### ISSUE THREAD

**Issue by cilliemalan** [RetroRabbit/rabbiteer-intern-project#23]
![image](https://cloud.githubusercontent.com/assets/3305301/10245246/01751352-6906-11e5-8d2a-9fb7ec8df73f.png)
![image](https://cloud.githubusercontent.com/assets/3305301/10245247/06d3ae80-6906-11e5-8ba0-66f3755f5e4c.png)

**Comment by cilliemalan** [comment]
My name is "Cillié"

**Comment by Mor1quendi** [comment]
Bug won't fix -> doesnt display special characters
